"""modified Product models

Revision ID: 13967979b6ce
Revises: ef857124cd4f
Create Date: 2026-05-20 18:00:28.034083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13967979b6ce'
down_revision = 'ef857124cd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('custom_fields_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('custom_fields_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
