"""modified CustomFields model

Revision ID: 45ad67a77fc6
Revises: 6014571db5de
Create Date: 2026-05-20 09:20:12.315022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ad67a77fc6'
down_revision = '6014571db5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customfields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customfields', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
