"""upgrade product model, add visiblate

Revision ID: 8f3b0c208965
Revises: ce25c6c4c74d
Create Date: 2025-11-28 11:59:39.352028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3b0c208965'
down_revision = 'ce25c6c4c74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
