"""Add image path to Promotions model

Revision ID: ddb8f121cf6d
Revises: fa26f9b6c745
Create Date: 2025-11-21 14:12:09.313949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb8f121cf6d'
down_revision = 'fa26f9b6c745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
