"""empty message

Revision ID: 196d5e0895a7
Revises: 7761df8c412a
Create Date: 2026-06-19 15:44:59.532553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196d5e0895a7'
down_revision = '7761df8c412a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery', sa.Boolean(), nullable=True))
        batch_op.drop_column('delyvery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delyvery', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('delivery')

    # ### end Alembic commands ###
